class FailedCallException implements Exception {
  const FailedCallException();
}
